// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Gem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ____Gem_h__
#define ____Gem_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/GCObject.h>
#include <Ice/AsyncResult.h>
#include <Ice/Incoming.h>
#include <Ice/IncomingAsync.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace Gem
{

class GemServer;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Gem::GemServer>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Gem::GemServer*);

}

}

namespace Gem
{

class GemServer;
bool operator==(const GemServer&, const GemServer&);
bool operator<(const GemServer&, const GemServer&);
::Ice::Object* upCast(::Gem::GemServer*);
typedef ::IceInternal::Handle< ::Gem::GemServer> GemServerPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Gem::GemServer> GemServerPrx;
void __patch(GemServerPtr&, const ::Ice::ObjectPtr&);

}

namespace Gem
{

typedef ::std::vector< ::std::string> StringSeq;

typedef ::std::map< ::std::string, ::std::string> StringStringDict;

enum JobState
{
    BLOCKED,
    STARTABLE,
    SCHEDULED,
    STARTED,
    STOPPED,
    FAILED,
    WAIVERED,
    COMPLETED
};

struct JobUpdate
{
    ::std::string id;
    ::Ice::Int pctComplete;
    ::std::string status;

    bool operator==(const JobUpdate& __rhs) const
    {
        if(this == &__rhs)
        {
            return true;
        }
        if(id != __rhs.id)
        {
            return false;
        }
        if(pctComplete != __rhs.pctComplete)
        {
            return false;
        }
        if(status != __rhs.status)
        {
            return false;
        }
        return true;
    }

    bool operator<(const JobUpdate& __rhs) const
    {
        if(this == &__rhs)
        {
            return false;
        }
        if(id < __rhs.id)
        {
            return true;
        }
        else if(__rhs.id < id)
        {
            return false;
        }
        if(pctComplete < __rhs.pctComplete)
        {
            return true;
        }
        else if(__rhs.pctComplete < pctComplete)
        {
            return false;
        }
        if(status < __rhs.status)
        {
            return true;
        }
        else if(__rhs.status < status)
        {
            return false;
        }
        return false;
    }

    bool operator!=(const JobUpdate& __rhs) const
    {
        return !operator==(__rhs);
    }
    bool operator<=(const JobUpdate& __rhs) const
    {
        return operator<(__rhs) || operator==(__rhs);
    }
    bool operator>(const JobUpdate& __rhs) const
    {
        return !operator<(__rhs) && !operator==(__rhs);
    }
    bool operator>=(const JobUpdate& __rhs) const
    {
        return !operator<(__rhs);
    }
};

typedef ::std::vector< ::Gem::JobUpdate> JobUpdateSeq;

struct JobWorkerState
{
    ::std::string id;
    ::Gem::JobState state;

    bool operator==(const JobWorkerState& __rhs) const
    {
        if(this == &__rhs)
        {
            return true;
        }
        if(id != __rhs.id)
        {
            return false;
        }
        if(state != __rhs.state)
        {
            return false;
        }
        return true;
    }

    bool operator<(const JobWorkerState& __rhs) const
    {
        if(this == &__rhs)
        {
            return false;
        }
        if(id < __rhs.id)
        {
            return true;
        }
        else if(__rhs.id < id)
        {
            return false;
        }
        if(state < __rhs.state)
        {
            return true;
        }
        else if(__rhs.state < state)
        {
            return false;
        }
        return false;
    }

    bool operator!=(const JobWorkerState& __rhs) const
    {
        return !operator==(__rhs);
    }
    bool operator<=(const JobWorkerState& __rhs) const
    {
        return operator<(__rhs) || operator==(__rhs);
    }
    bool operator>(const JobWorkerState& __rhs) const
    {
        return !operator<(__rhs) && !operator==(__rhs);
    }
    bool operator>=(const JobWorkerState& __rhs) const
    {
        return !operator<(__rhs);
    }
};

struct Job
{
    Job() :
        state(STARTABLE)
    {
    }
    
    Job(const ::std::string& __ice_id, ::Ice::Int __ice_priority, ::Gem::JobState __ice_state, const ::std::string& __ice_pwd, const ::Gem::StringSeq& __ice_cmdLine, const ::Gem::StringStringDict& __ice_env, const ::Gem::StringSeq& __ice_dependencies) :
        id(__ice_id),
        priority(__ice_priority),
        state(__ice_state),
        pwd(__ice_pwd),
        cmdLine(__ice_cmdLine),
        env(__ice_env),
        dependencies(__ice_dependencies)
    {
    }
    

    ::std::string id;
    ::Ice::Int priority;
    ::Gem::JobState state;
    ::std::string pwd;
    ::Gem::StringSeq cmdLine;
    ::Gem::StringStringDict env;
    ::Gem::StringSeq dependencies;
};

typedef ::std::vector< ::Gem::Job> JobSeq;

typedef ::std::map< ::std::string, ::Gem::Job> JobDict;

struct Batch
{
    ::Gem::JobSeq jobs;
};

struct WorkerId
{
    ::std::string id;

    bool operator==(const WorkerId& __rhs) const
    {
        if(this == &__rhs)
        {
            return true;
        }
        if(id != __rhs.id)
        {
            return false;
        }
        return true;
    }

    bool operator<(const WorkerId& __rhs) const
    {
        if(this == &__rhs)
        {
            return false;
        }
        if(id < __rhs.id)
        {
            return true;
        }
        else if(__rhs.id < id)
        {
            return false;
        }
        return false;
    }

    bool operator!=(const WorkerId& __rhs) const
    {
        return !operator==(__rhs);
    }
    bool operator<=(const WorkerId& __rhs) const
    {
        return operator<(__rhs) || operator==(__rhs);
    }
    bool operator>(const WorkerId& __rhs) const
    {
        return !operator<(__rhs) && !operator==(__rhs);
    }
    bool operator>=(const WorkerId& __rhs) const
    {
        return !operator<(__rhs);
    }
};

}

namespace Ice
{
template<>
struct StreamableTraits< ::Gem::JobState>
{
    static const StreamHelperCategory helper = StreamHelperCategoryEnum;
    static const int minValue = 0;
    static const int maxValue = 7;
    static const int minWireSize = 1;
    static const bool fixedLength = false;
};

template<>
struct StreamableTraits< ::Gem::JobUpdate>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 6;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::Gem::JobUpdate, S>
{
    static void write(S* __os, const ::Gem::JobUpdate& v)
    {
        __os->write(v.id);
        __os->write(v.pctComplete);
        __os->write(v.status);
    }
};

template<class S>
struct StreamReader< ::Gem::JobUpdate, S>
{
    static void read(S* __is, ::Gem::JobUpdate& v)
    {
        __is->read(v.id);
        __is->read(v.pctComplete);
        __is->read(v.status);
    }
};

template<>
struct StreamableTraits< ::Gem::JobWorkerState>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 2;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::Gem::JobWorkerState, S>
{
    static void write(S* __os, const ::Gem::JobWorkerState& v)
    {
        __os->write(v.id);
        __os->write(v.state);
    }
};

template<class S>
struct StreamReader< ::Gem::JobWorkerState, S>
{
    static void read(S* __is, ::Gem::JobWorkerState& v)
    {
        __is->read(v.id);
        __is->read(v.state);
    }
};

template<>
struct StreamableTraits< ::Gem::Job>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 10;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::Gem::Job, S>
{
    static void write(S* __os, const ::Gem::Job& v)
    {
        __os->write(v.id);
        __os->write(v.priority);
        __os->write(v.state);
        __os->write(v.pwd);
        __os->write(v.cmdLine);
        __os->write(v.env);
        __os->write(v.dependencies);
    }
};

template<class S>
struct StreamReader< ::Gem::Job, S>
{
    static void read(S* __is, ::Gem::Job& v)
    {
        __is->read(v.id);
        __is->read(v.priority);
        __is->read(v.state);
        __is->read(v.pwd);
        __is->read(v.cmdLine);
        __is->read(v.env);
        __is->read(v.dependencies);
    }
};

template<>
struct StreamableTraits< ::Gem::Batch>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 1;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::Gem::Batch, S>
{
    static void write(S* __os, const ::Gem::Batch& v)
    {
        __os->write(v.jobs);
    }
};

template<class S>
struct StreamReader< ::Gem::Batch, S>
{
    static void read(S* __is, ::Gem::Batch& v)
    {
        __is->read(v.jobs);
    }
};

template<>
struct StreamableTraits< ::Gem::WorkerId>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 1;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::Gem::WorkerId, S>
{
    static void write(S* __os, const ::Gem::WorkerId& v)
    {
        __os->write(v.id);
    }
};

template<class S>
struct StreamReader< ::Gem::WorkerId, S>
{
    static void read(S* __is, ::Gem::WorkerId& v)
    {
        __is->read(v.id);
    }
};

}

namespace Gem
{

class AMD_GemServer_submitBatch : virtual public ::Ice::AMDCallback
{
public:

    virtual void ice_response() = 0;
};

typedef ::IceUtil::Handle< ::Gem::AMD_GemServer_submitBatch> AMD_GemServer_submitBatchPtr;

class AMD_GemServer_startJob : virtual public ::Ice::AMDCallback
{
public:

    virtual void ice_response() = 0;
};

typedef ::IceUtil::Handle< ::Gem::AMD_GemServer_startJob> AMD_GemServer_startJobPtr;

class AMD_GemServer_stopJob : virtual public ::Ice::AMDCallback
{
public:

    virtual void ice_response() = 0;
};

typedef ::IceUtil::Handle< ::Gem::AMD_GemServer_stopJob> AMD_GemServer_stopJobPtr;

class AMD_GemServer_invalidate : virtual public ::Ice::AMDCallback
{
public:

    virtual void ice_response() = 0;
};

typedef ::IceUtil::Handle< ::Gem::AMD_GemServer_invalidate> AMD_GemServer_invalidatePtr;

class AMD_GemServer_getJobs : virtual public ::Ice::AMDCallback
{
public:

    virtual void ice_response(const ::Gem::JobDict&) = 0;
};

typedef ::IceUtil::Handle< ::Gem::AMD_GemServer_getJobs> AMD_GemServer_getJobsPtr;

class AMD_GemServer_getStartableJob : virtual public ::Ice::AMDCallback
{
public:

    virtual void ice_response(const ::Gem::JobSeq&) = 0;
};

typedef ::IceUtil::Handle< ::Gem::AMD_GemServer_getStartableJob> AMD_GemServer_getStartableJobPtr;

}

namespace IceAsync
{

namespace Gem
{

class AMD_GemServer_submitBatch : public ::Gem::AMD_GemServer_submitBatch, public ::IceInternal::IncomingAsync
{
public:

    AMD_GemServer_submitBatch(::IceInternal::Incoming&);

    virtual void ice_response();
};

class AMD_GemServer_startJob : public ::Gem::AMD_GemServer_startJob, public ::IceInternal::IncomingAsync
{
public:

    AMD_GemServer_startJob(::IceInternal::Incoming&);

    virtual void ice_response();
};

class AMD_GemServer_stopJob : public ::Gem::AMD_GemServer_stopJob, public ::IceInternal::IncomingAsync
{
public:

    AMD_GemServer_stopJob(::IceInternal::Incoming&);

    virtual void ice_response();
};

class AMD_GemServer_invalidate : public ::Gem::AMD_GemServer_invalidate, public ::IceInternal::IncomingAsync
{
public:

    AMD_GemServer_invalidate(::IceInternal::Incoming&);

    virtual void ice_response();
};

class AMD_GemServer_getJobs : public ::Gem::AMD_GemServer_getJobs, public ::IceInternal::IncomingAsync
{
public:

    AMD_GemServer_getJobs(::IceInternal::Incoming&);

    virtual void ice_response(const ::Gem::JobDict&);
};

class AMD_GemServer_getStartableJob : public ::Gem::AMD_GemServer_getStartableJob, public ::IceInternal::IncomingAsync
{
public:

    AMD_GemServer_getStartableJob(::IceInternal::Incoming&);

    virtual void ice_response(const ::Gem::JobSeq&);
};

}

}

namespace Gem
{

class Callback_GemServer_submitBatch_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GemServer_submitBatch_Base> Callback_GemServer_submitBatchPtr;

class Callback_GemServer_startJob_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GemServer_startJob_Base> Callback_GemServer_startJobPtr;

class Callback_GemServer_stopJob_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GemServer_stopJob_Base> Callback_GemServer_stopJobPtr;

class Callback_GemServer_invalidate_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GemServer_invalidate_Base> Callback_GemServer_invalidatePtr;

class Callback_GemServer_getJobs_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GemServer_getJobs_Base> Callback_GemServer_getJobsPtr;

class Callback_GemServer_getStartableJob_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GemServer_getStartableJob_Base> Callback_GemServer_getStartableJobPtr;

}

namespace IceProxy
{

namespace Gem
{

class GemServer : virtual public ::IceProxy::Ice::Object
{
public:

    void submitBatch(const ::Gem::Batch& __p_batch)
    {
        submitBatch(__p_batch, 0);
    }
    void submitBatch(const ::Gem::Batch& __p_batch, const ::Ice::Context& __ctx)
    {
        submitBatch(__p_batch, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_submitBatch(const ::Gem::Batch& __p_batch, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_submitBatch(__p_batch, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_submitBatch(const ::Gem::Batch& __p_batch, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_submitBatch(__p_batch, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_submitBatch(const ::Gem::Batch& __p_batch, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_submitBatch(__p_batch, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_submitBatch(const ::Gem::Batch& __p_batch, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_submitBatch(__p_batch, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_submitBatch(const ::Gem::Batch& __p_batch)
    {
        return begin_submitBatch(__p_batch, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_submitBatch(const ::Gem::Batch& __p_batch, const ::Ice::Context& __ctx)
    {
        return begin_submitBatch(__p_batch, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_submitBatch(const ::Gem::Batch& __p_batch, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_submitBatch(__p_batch, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_submitBatch(const ::Gem::Batch& __p_batch, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_submitBatch(__p_batch, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_submitBatch(const ::Gem::Batch& __p_batch, const ::Gem::Callback_GemServer_submitBatchPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_submitBatch(__p_batch, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_submitBatch(const ::Gem::Batch& __p_batch, const ::Ice::Context& __ctx, const ::Gem::Callback_GemServer_submitBatchPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_submitBatch(__p_batch, &__ctx, __del, __cookie);
    }

    void end_submitBatch(const ::Ice::AsyncResultPtr&);
    
private:

    void submitBatch(const ::Gem::Batch&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_submitBatch(const ::Gem::Batch&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void startJob(const ::std::string& __p_id)
    {
        startJob(__p_id, 0);
    }
    void startJob(const ::std::string& __p_id, const ::Ice::Context& __ctx)
    {
        startJob(__p_id, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_startJob(const ::std::string& __p_id, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_startJob(__p_id, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_startJob(const ::std::string& __p_id, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_startJob(__p_id, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_startJob(const ::std::string& __p_id, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_startJob(__p_id, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_startJob(const ::std::string& __p_id, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_startJob(__p_id, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_startJob(const ::std::string& __p_id)
    {
        return begin_startJob(__p_id, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_startJob(const ::std::string& __p_id, const ::Ice::Context& __ctx)
    {
        return begin_startJob(__p_id, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_startJob(const ::std::string& __p_id, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_startJob(__p_id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_startJob(const ::std::string& __p_id, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_startJob(__p_id, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_startJob(const ::std::string& __p_id, const ::Gem::Callback_GemServer_startJobPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_startJob(__p_id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_startJob(const ::std::string& __p_id, const ::Ice::Context& __ctx, const ::Gem::Callback_GemServer_startJobPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_startJob(__p_id, &__ctx, __del, __cookie);
    }

    void end_startJob(const ::Ice::AsyncResultPtr&);
    
private:

    void startJob(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_startJob(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void stopJob(const ::std::string& __p_id)
    {
        stopJob(__p_id, 0);
    }
    void stopJob(const ::std::string& __p_id, const ::Ice::Context& __ctx)
    {
        stopJob(__p_id, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_stopJob(const ::std::string& __p_id, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_stopJob(__p_id, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_stopJob(const ::std::string& __p_id, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_stopJob(__p_id, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_stopJob(const ::std::string& __p_id, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_stopJob(__p_id, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_stopJob(const ::std::string& __p_id, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_stopJob(__p_id, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_stopJob(const ::std::string& __p_id)
    {
        return begin_stopJob(__p_id, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_stopJob(const ::std::string& __p_id, const ::Ice::Context& __ctx)
    {
        return begin_stopJob(__p_id, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_stopJob(const ::std::string& __p_id, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_stopJob(__p_id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_stopJob(const ::std::string& __p_id, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_stopJob(__p_id, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_stopJob(const ::std::string& __p_id, const ::Gem::Callback_GemServer_stopJobPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_stopJob(__p_id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_stopJob(const ::std::string& __p_id, const ::Ice::Context& __ctx, const ::Gem::Callback_GemServer_stopJobPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_stopJob(__p_id, &__ctx, __del, __cookie);
    }

    void end_stopJob(const ::Ice::AsyncResultPtr&);
    
private:

    void stopJob(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_stopJob(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void invalidate(const ::std::string& __p_id)
    {
        invalidate(__p_id, 0);
    }
    void invalidate(const ::std::string& __p_id, const ::Ice::Context& __ctx)
    {
        invalidate(__p_id, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_invalidate(const ::std::string& __p_id, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_invalidate(__p_id, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_invalidate(const ::std::string& __p_id, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_invalidate(__p_id, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_invalidate(const ::std::string& __p_id, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_invalidate(__p_id, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_invalidate(const ::std::string& __p_id, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_invalidate(__p_id, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_invalidate(const ::std::string& __p_id)
    {
        return begin_invalidate(__p_id, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_invalidate(const ::std::string& __p_id, const ::Ice::Context& __ctx)
    {
        return begin_invalidate(__p_id, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_invalidate(const ::std::string& __p_id, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_invalidate(__p_id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_invalidate(const ::std::string& __p_id, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_invalidate(__p_id, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_invalidate(const ::std::string& __p_id, const ::Gem::Callback_GemServer_invalidatePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_invalidate(__p_id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_invalidate(const ::std::string& __p_id, const ::Ice::Context& __ctx, const ::Gem::Callback_GemServer_invalidatePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_invalidate(__p_id, &__ctx, __del, __cookie);
    }

    void end_invalidate(const ::Ice::AsyncResultPtr&);
    
private:

    void invalidate(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_invalidate(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Gem::JobDict getJobs()
    {
        return getJobs(0);
    }
    ::Gem::JobDict getJobs(const ::Ice::Context& __ctx)
    {
        return getJobs(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_getJobs(const ::IceInternal::Function<void (const ::Gem::JobDict&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getJobs(0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getJobs(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getJobs(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getJobs(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Gem::JobDict&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getJobs(&__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getJobs(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getJobs(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_getJobs(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::Gem::JobDict&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_getJobs()
    {
        return begin_getJobs(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getJobs(const ::Ice::Context& __ctx)
    {
        return begin_getJobs(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getJobs(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getJobs(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getJobs(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getJobs(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getJobs(const ::Gem::Callback_GemServer_getJobsPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getJobs(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getJobs(const ::Ice::Context& __ctx, const ::Gem::Callback_GemServer_getJobsPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getJobs(&__ctx, __del, __cookie);
    }

    ::Gem::JobDict end_getJobs(const ::Ice::AsyncResultPtr&);
    
private:

    ::Gem::JobDict getJobs(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getJobs(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Gem::JobSeq getStartableJob(const ::Gem::WorkerId& __p_worker)
    {
        return getStartableJob(__p_worker, 0);
    }
    ::Gem::JobSeq getStartableJob(const ::Gem::WorkerId& __p_worker, const ::Ice::Context& __ctx)
    {
        return getStartableJob(__p_worker, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_getStartableJob(const ::Gem::WorkerId& __p_worker, const ::IceInternal::Function<void (const ::Gem::JobSeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getStartableJob(__p_worker, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getStartableJob(const ::Gem::WorkerId& __p_worker, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getStartableJob(__p_worker, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getStartableJob(const ::Gem::WorkerId& __p_worker, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Gem::JobSeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getStartableJob(__p_worker, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getStartableJob(const ::Gem::WorkerId& __p_worker, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getStartableJob(__p_worker, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_getStartableJob(const ::Gem::WorkerId& __p_worker, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::Gem::JobSeq&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_getStartableJob(const ::Gem::WorkerId& __p_worker)
    {
        return begin_getStartableJob(__p_worker, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getStartableJob(const ::Gem::WorkerId& __p_worker, const ::Ice::Context& __ctx)
    {
        return begin_getStartableJob(__p_worker, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getStartableJob(const ::Gem::WorkerId& __p_worker, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getStartableJob(__p_worker, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getStartableJob(const ::Gem::WorkerId& __p_worker, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getStartableJob(__p_worker, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getStartableJob(const ::Gem::WorkerId& __p_worker, const ::Gem::Callback_GemServer_getStartableJobPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getStartableJob(__p_worker, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getStartableJob(const ::Gem::WorkerId& __p_worker, const ::Ice::Context& __ctx, const ::Gem::Callback_GemServer_getStartableJobPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getStartableJob(__p_worker, &__ctx, __del, __cookie);
    }

    ::Gem::JobSeq end_getStartableJob(const ::Ice::AsyncResultPtr&);
    
private:

    ::Gem::JobSeq getStartableJob(const ::Gem::WorkerId&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getStartableJob(const ::Gem::WorkerId&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<GemServer> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<GemServer> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<GemServer> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<GemServer> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<GemServer> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<GemServer> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<GemServer> ice_secure(bool __secure) const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<GemServer> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<GemServer> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<GemServer> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<GemServer> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<GemServer> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<GemServer> ice_twoway() const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<GemServer> ice_oneway() const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<GemServer> ice_batchOneway() const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<GemServer> ice_datagram() const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<GemServer> ice_batchDatagram() const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<GemServer> ice_compress(bool __compress) const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<GemServer> ice_timeout(int __timeout) const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<GemServer> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<GemServer> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<GemServer*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace Gem
{

class GemServer : virtual public ::Ice::Object
{
public:

    typedef GemServerPrx ProxyType;
    typedef GemServerPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void submitBatch_async(const ::Gem::AMD_GemServer_submitBatchPtr&, const ::Gem::Batch&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___submitBatch(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void startJob_async(const ::Gem::AMD_GemServer_startJobPtr&, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___startJob(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void stopJob_async(const ::Gem::AMD_GemServer_stopJobPtr&, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___stopJob(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void invalidate_async(const ::Gem::AMD_GemServer_invalidatePtr&, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___invalidate(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void getJobs_async(const ::Gem::AMD_GemServer_getJobsPtr&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getJobs(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void getStartableJob_async(const ::Gem::AMD_GemServer_getStartableJobPtr&, const ::Gem::WorkerId&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getStartableJob(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
};

inline bool operator==(const GemServer& l, const GemServer& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const GemServer& l, const GemServer& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Gem
{

template<class T>
class CallbackNC_GemServer_submitBatch : public Callback_GemServer_submitBatch_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_GemServer_submitBatch(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_GemServer_submitBatchPtr
newCallback_GemServer_submitBatch(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GemServer_submitBatch<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GemServer_submitBatchPtr
newCallback_GemServer_submitBatch(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GemServer_submitBatch<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_GemServer_submitBatchPtr
newCallback_GemServer_submitBatch(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GemServer_submitBatch<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GemServer_submitBatchPtr
newCallback_GemServer_submitBatch(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GemServer_submitBatch<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_GemServer_submitBatch : public Callback_GemServer_submitBatch_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_GemServer_submitBatch(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_GemServer_submitBatchPtr
newCallback_GemServer_submitBatch(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GemServer_submitBatch<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GemServer_submitBatchPtr
newCallback_GemServer_submitBatch(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GemServer_submitBatch<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_GemServer_submitBatchPtr
newCallback_GemServer_submitBatch(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GemServer_submitBatch<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GemServer_submitBatchPtr
newCallback_GemServer_submitBatch(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GemServer_submitBatch<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_GemServer_startJob : public Callback_GemServer_startJob_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_GemServer_startJob(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_GemServer_startJobPtr
newCallback_GemServer_startJob(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GemServer_startJob<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GemServer_startJobPtr
newCallback_GemServer_startJob(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GemServer_startJob<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_GemServer_startJobPtr
newCallback_GemServer_startJob(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GemServer_startJob<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GemServer_startJobPtr
newCallback_GemServer_startJob(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GemServer_startJob<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_GemServer_startJob : public Callback_GemServer_startJob_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_GemServer_startJob(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_GemServer_startJobPtr
newCallback_GemServer_startJob(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GemServer_startJob<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GemServer_startJobPtr
newCallback_GemServer_startJob(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GemServer_startJob<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_GemServer_startJobPtr
newCallback_GemServer_startJob(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GemServer_startJob<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GemServer_startJobPtr
newCallback_GemServer_startJob(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GemServer_startJob<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_GemServer_stopJob : public Callback_GemServer_stopJob_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_GemServer_stopJob(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_GemServer_stopJobPtr
newCallback_GemServer_stopJob(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GemServer_stopJob<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GemServer_stopJobPtr
newCallback_GemServer_stopJob(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GemServer_stopJob<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_GemServer_stopJobPtr
newCallback_GemServer_stopJob(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GemServer_stopJob<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GemServer_stopJobPtr
newCallback_GemServer_stopJob(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GemServer_stopJob<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_GemServer_stopJob : public Callback_GemServer_stopJob_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_GemServer_stopJob(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_GemServer_stopJobPtr
newCallback_GemServer_stopJob(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GemServer_stopJob<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GemServer_stopJobPtr
newCallback_GemServer_stopJob(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GemServer_stopJob<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_GemServer_stopJobPtr
newCallback_GemServer_stopJob(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GemServer_stopJob<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GemServer_stopJobPtr
newCallback_GemServer_stopJob(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GemServer_stopJob<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_GemServer_invalidate : public Callback_GemServer_invalidate_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_GemServer_invalidate(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_GemServer_invalidatePtr
newCallback_GemServer_invalidate(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GemServer_invalidate<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GemServer_invalidatePtr
newCallback_GemServer_invalidate(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GemServer_invalidate<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_GemServer_invalidatePtr
newCallback_GemServer_invalidate(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GemServer_invalidate<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GemServer_invalidatePtr
newCallback_GemServer_invalidate(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GemServer_invalidate<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_GemServer_invalidate : public Callback_GemServer_invalidate_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_GemServer_invalidate(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_GemServer_invalidatePtr
newCallback_GemServer_invalidate(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GemServer_invalidate<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GemServer_invalidatePtr
newCallback_GemServer_invalidate(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GemServer_invalidate<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_GemServer_invalidatePtr
newCallback_GemServer_invalidate(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GemServer_invalidate<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GemServer_invalidatePtr
newCallback_GemServer_invalidate(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GemServer_invalidate<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_GemServer_getJobs : public Callback_GemServer_getJobs_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Gem::JobDict&);

    CallbackNC_GemServer_getJobs(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Gem::GemServerPrx __proxy = ::Gem::GemServerPrx::uncheckedCast(__result->getProxy());
        ::Gem::JobDict __ret;
        try
        {
            __ret = __proxy->end_getJobs(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_GemServer_getJobsPtr
newCallback_GemServer_getJobs(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Gem::JobDict&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GemServer_getJobs<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GemServer_getJobsPtr
newCallback_GemServer_getJobs(T* instance, void (T::*cb)(const ::Gem::JobDict&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GemServer_getJobs<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_GemServer_getJobs : public Callback_GemServer_getJobs_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Gem::JobDict&, const CT&);

    Callback_GemServer_getJobs(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Gem::GemServerPrx __proxy = ::Gem::GemServerPrx::uncheckedCast(__result->getProxy());
        ::Gem::JobDict __ret;
        try
        {
            __ret = __proxy->end_getJobs(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_GemServer_getJobsPtr
newCallback_GemServer_getJobs(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Gem::JobDict&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GemServer_getJobs<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GemServer_getJobsPtr
newCallback_GemServer_getJobs(T* instance, void (T::*cb)(const ::Gem::JobDict&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GemServer_getJobs<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_GemServer_getStartableJob : public Callback_GemServer_getStartableJob_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Gem::JobSeq&);

    CallbackNC_GemServer_getStartableJob(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Gem::GemServerPrx __proxy = ::Gem::GemServerPrx::uncheckedCast(__result->getProxy());
        ::Gem::JobSeq __ret;
        try
        {
            __ret = __proxy->end_getStartableJob(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_GemServer_getStartableJobPtr
newCallback_GemServer_getStartableJob(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Gem::JobSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GemServer_getStartableJob<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GemServer_getStartableJobPtr
newCallback_GemServer_getStartableJob(T* instance, void (T::*cb)(const ::Gem::JobSeq&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GemServer_getStartableJob<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_GemServer_getStartableJob : public Callback_GemServer_getStartableJob_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Gem::JobSeq&, const CT&);

    Callback_GemServer_getStartableJob(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Gem::GemServerPrx __proxy = ::Gem::GemServerPrx::uncheckedCast(__result->getProxy());
        ::Gem::JobSeq __ret;
        try
        {
            __ret = __proxy->end_getStartableJob(__result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_GemServer_getStartableJobPtr
newCallback_GemServer_getStartableJob(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Gem::JobSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GemServer_getStartableJob<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GemServer_getStartableJobPtr
newCallback_GemServer_getStartableJob(T* instance, void (T::*cb)(const ::Gem::JobSeq&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GemServer_getStartableJob<T, CT>(instance, cb, excb, sentcb);
}

}

#include <IceUtil/PopDisableWarnings.h>
#endif
