import builders
from os.path import expanduser as eu

spdlog = '-I%s' % eu('~/repos/spdlog/include')

env = Environment(CPPFLAGS = ['--std=c++14', '-I.', spdlog ],
                  SLICE_INCLUDES= ['/usr/share/ice/slice'],
                  LIBPATH = ['/usr/lib/x86_64-linux-gnu/c++11'])

#env.Slice2cpp(target = 'Security', source = 'slice/Security.ice')
builders.addSlice2cppBuilder(env)

env.Slice2cpp(target = 'scheduler.cpp',
              source = '../slice/scheduler.ice')

scheduler = env.Object(source = 'scheduler.cpp')

env.Program('schedulerServer.cpp', LIBS = [scheduler, 'Ice', 'IceUtil', 'IceStorm','pthread'])
