import builders
from os.path import expanduser as eu

spdlog = '-I%s' % eu('~/repos/spdlog/include')

env = Environment(CPPFLAGS = ['-DICE_CPP11_MAPPING', '--std=c++14', '-I.', spdlog ],
                  SLICE_INCLUDES= ['/usr/share/Ice-3.6.1/slice'],
                  LIBPATH = ['/usr/lib/x86_64-linux-gnu/c++11'])

#env.Slice2cpp(target = 'Security', source = 'slice/Security.ice')
builders.addSlice2cppBuilder(env)

env.Slice2cpp(target = 'gem.cpp',
              source = '../slice/gem.ice')

gem = env.Object(source = 'gem.cpp')

env.Program('gemServer.cpp', LIBS = [gem, 'Ice', 'IceUtil', 'IceStorm','pthread'])
